spring.application.name=Bank
spring.datasource.url=jdbc:postgresql://localhost:5432/my_app
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=Claudia123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=zangooctavio340@gmail.com
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
jwt.secret=${JWT_SECRET}